baseURL = 'https://xiaogongzhuuu.github.io/'
locale = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = '一只老红薯'
theme = 'PaperMod'

enableRobotsTXT = true
paginate = 8

[taxonomies]
category = 'categories'
tag = 'tags'

[params]
env = 'production'
description = '探索AI浪潮中的人性、秩序与未来。'
author = '一只老红薯'
mainSections = []
DateFormat = '2006年1月2日'
defaultTheme = 'light'
disableThemeToggle = true
ShowReadingTime = false
ShowShareButtons = true
ShareButtons = ['x', 'telegram']
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = false
ShowToc = true

[params.assets]
theme_color = '#ffffff'

[params.homeInfoParams]
Title = '一只老红薯'
Content = '探索AI浪潮中的人性、秩序与未来。'

[[params.socialIcons]]
name = 'GitHub'
url = 'https://github.com/xiaogongzhuuu'

[[params.socialIcons]]
name = '小红书'
url = 'https://www.xiaohongshu.com/user/profile/6301d55f0000000012001c6a'

[params.giscus]
enabled = true
repo = 'xiaogongzhuuu/xiaogongzhuuu.github.io'
repoID = 'R_kgDOUAuxFw'
category = 'Announcements'
categoryID = 'DIC_kwDOUAuxF84DD_JU'
mapping = 'pathname'
lang = 'zh-CN'
