baseURL = 'https://xiaogongzhuuu.github.io/'
locale = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = "xiaogongzhuuu's Blog"
theme = 'PaperMod'

enableRobotsTXT = true
paginate = 8

[taxonomies]
category = 'categories'
tag = 'tags'

[params]
env = 'production'
description = '在技术、商业与社会的交叉处,观察变化,记录思考。'
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowToc = true

[params.homeInfoParams]
Title = '你好 👋'
Content = '在技术、商业与社会的交叉处,观察变化,记录思考。'

[[params.socialIcons]]
name = 'GitHub'
url = 'https://github.com/xiaogongzhuuu'

[[menu.main]]
name = '归档'
url = '/archives/'
weight = 10

[[menu.main]]
name = '标签'
url = '/tags/'
weight = 20

[[menu.main]]
name = '关于'
url = '/about/'
weight = 30
